---
- name: Configure options in /boot/config.txt.
  lineinfile:
    dest: /boot/config.txt
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: EOF
    state: present
  with_items: "{{ raspberry_pi_boot_config_options }}"

- name: Configure options in /etc/rc.local.
  lineinfile:
    dest: /etc/rc.local
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "^exit"
    state: present
  with_items: "{{ raspberry_pi_rc_local_options }}"

# Update system
- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

- name: Check if upgrades are available
  command: apt list --upgradable
  register: apt_upgradable
  changed_when: apt_upgradable.stdout_lines | length > 1
  become: true

- name: Upgrade all packages if updates are available
  apt:
    upgrade: dist
  become: true
  when: apt_upgradable.stdout_lines | length > 1

- name: Check if a reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot the system if required
  reboot:
  become: true
  when: reboot_required.stat.exists

# Set the timezone
- name: Check current timezone
  command: timedatectl show --property=Timezone --value
  register: current_timezone
  changed_when: false

- name: Set timezone to Central Time (America/Chicago) if needed
  command: timedatectl set-timezone America/Chicago
  become: true
  when: current_timezone.stdout != "America/Chicago"

# Call other scripts
- name: Add nightly updates
  ansible.builtin.import_tasks: nightly-update.yml

- name: Enable the oled screen
  ansible.builtin.import_tasks: oled-screen.yml

- name: Add Static Networking
  ansible.builtin.import_tasks: static-networking.yml