---
# Add nightly update script
- name: Copy update script to /usr/local/bin
  copy:
    src: update.sh
    dest: /usr/local/bin/update-system.sh
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Add cron job for automatic updates
  cron:
    name: "Nightly system update"
    job: "/usr/local/bin/update-system.sh"
    minute: "0"
    hour: "2"
    user: "root"
  become: true